### PR TITLE
Fix #15

### LINKED ISSUE #15: ⚙️ for-all-boosters: rework create_branch and delete_branch commands to use specified branch names
… instead of having to provide one as subcommand argument.

### PR DESCRIPTION
**Pull request by metacosm**

### CODE REVIEW

**Comment by geoand** [comment]
It seems like we have conflicts. Can you please check it out @metacosm ?

**Comment by metacosm** [comment]
Conflicts fixed.

**Comment by geoand** [comment]
Do we usually squash commits in PRs or not?

**Comment by metacosm** [comment]
I just rebase and merge but we can squash, as well…

**Comment by geoand** [comment]
No need, just asking so I can now which button to push :)

**Pull request merged**
