### PR TITLE
Fix final result output

### LINKED ISSUE #7: 🐛 for-all-boosters: fix output of failed / ignored / processed boosters
- indicated cardinality is incorrect
- improve output to display each item on its own line, possibly grouping by branch

### PR DESCRIPTION
**Pull request by geoand**
Fixes #7

### CODE REVIEW

**Comment by geoand** [comment]
The grouping functionality mentioned in the issue has not been implemented

**Comment by geoand** [comment]
I looked into to trying to implement grouping using associative arrays, but that does not work out too well because you can't assign arrays to values of an associative array :(
The desired grouping functionality is probably possible using perl or awk, but I think that the gain does not outweigh the effort needed to develop the solution

**Comment by metacosm** [comment]
Let's forget about grouping, it'd be nice to have but it's definitely not worth the effort!
Thank you!

**Comment by geoand** [comment]
You are welcome! 

I completely agree about the grouping feature :)

**Pull request merged**
