### PR TITLE
Fix subcommand option parsing issue

### PR DESCRIPTION
**Pull request by geoand**
Fixes: #3

### CODE REVIEW

**Comment by metacosm** [comment]
I’m afraid that won’t work if we have more than 2 options

**Comment by geoand** [comment]
I tried it by adding a new dummy option and it did work.
Please give it a try as well and let me know :)

**Comment by metacosm** [comment]
@geoand could you elaborate on why this fixes the issue, actually? :)

**Comment by geoand** [comment]
It fixes the issue because `getopts` needs to in a sense start over when parsing the options of the subcommand regardless of the number of options it parsed for the command.

**Comment by metacosm** [comment]
@geoand I thought that was the purpose of: https://github.com/snowdrop/booster-common/blob/master/for-all-boosters.sh#L405
Also, why the magic number `2`?

**Comment by geoand** [comment]
The line you mention shifts the parameters passed to the script so you can easily get the arguments you need later on using `$1` `$2` etc.
`getopts` keeps track of the next argument it has to process using `OPTIND`.

As for the number itself, I am not sure to tell you the truth... I expected to have to set it to `1` (which is the initial value of `OPTIND`) not `2`. 
But `2` is what works as I figured out via debugging...

**Pull request merged**
