### PR TITLE
Add support for custom settings.xml file

### PR DESCRIPTION
**Pull request by geoand**
The custom settings xml file can be very useful for resolving
productized Red Hat artifacts

### CODE REVIEW

**Comment by metacosm** [comment]
@geoand nope, it's specifically for the changes introduced in this PR… :)
Not sure if it's a false positive, though…

**Comment by geoand** [comment]
What puzzles me is that I haven't added any quotes (single or double)... So I don't really know what to check here...

**Comment by metacosm** [comment]
Indeed… My guess is that it picked up the `'${'${1}'}'` part from before… but I'm really not sure… Let's ignore this for now.

**Comment by geoand** [comment]
OK, thanks!

**Pull request merged**
